name: Verify module

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  verify-module:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install uxsim and dependencies
      run: pip install .
    - name: Install pytest other dependencies
      run: pip install pytest pytest-rerunfailures setuptools
    - name: Run verifications with pytest
      run: pytest tests/test_verification_straight_road.py tests/test_verification_route_choice.py tests/test_verification_node.py tests/test_verification_exceptional.py tests/test_verification_sioux_falls.py tests/test_verification_multilane.py --durations=0 -v
